config/routes.rb
Rails.application.routes.draw do
  resources :vishnus
  resources :sharans
  resources :nisargas
  resources :chetans
  

end

app/models/chetan.rb
class Chetan < ActiveRecord::Base
end

app/models/nisarga.rb
class Nisarga < ActiveRecord::Base
end

app/models/sharan.rb
class Sharan < ActiveRecord::Base
end

app/models/vishnu.rb
class Vishnu < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cheta_ns_controller.rb
class ChetaNsController < ApplicationController
  before_action :set_chetan, only: [:show, :edit, :update, :destroy]

  # GET /chetans
  # GET /chetans.json
  def index
    @chetans = Chetan.all
  end

  # GET /chetans/1
  # GET /chetans/1.json
  def show
  end

  # GET /chetans/new
  def new
    @chetan = Chetan.new
  end

  # GET /chetans/1/edit
  def edit
  end

  # POST /chetans
  # POST /chetans.json
  def create
    @chetan = Chetan.new(chetan_params)

    respond_to do |format|
      if @chetan.save
        format.html { redirect_to @chetan, notice: 'Chetan was successfully created.' }
        format.json { render :show, status: :created, location: @chetan }
      else
        format.html { render :new }
        format.json { render json: @chetan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chetans/1
  # PATCH/PUT /chetans/1.json
  def update
    respond_to do |format|
      if @chetan.update(chetan_params)
        format.html { redirect_to @chetan, notice: 'Chetan was successfully updated.' }
        format.json { render :show, status: :ok, location: @chetan }
      else
        format.html { render :edit }
        format.json { render json: @chetan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chetans/1
  # DELETE /chetans/1.json
  def destroy
    @chetan.destroy
    respond_to do |format|
      format.html { redirect_to chetans_url, notice: 'Chetan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chetan
      @chetan = Chetan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chetan_params
      params.require(:chetan).permit(:name, :commit_id)
    end
end

app/controllers/nisargas_controller.rb
class NisargasController < ApplicationController
  before_action :set_nisarga, only: [:show, :edit, :update, :destroy]

  # GET /nisargas
  # GET /nisargas.json
  def index
    @nisargas = Nisarga.all
  end

  # GET /nisargas/1
  # GET /nisargas/1.json
  def show
  end

  # GET /nisargas/new
  def new
    @nisarga = Nisarga.new
  end

  # GET /nisargas/1/edit
  def edit
  end

  # POST /nisargas
  # POST /nisargas.json
  def create
    @nisarga = Nisarga.new(nisarga_params)

    respond_to do |format|
      if @nisarga.save
        format.html { redirect_to @nisarga, notice: 'Nisarga was successfully created.' }
        format.json { render :show, status: :created, location: @nisarga }
      else
        format.html { render :new }
        format.json { render json: @nisarga.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nisargas/1
  # PATCH/PUT /nisargas/1.json
  def update
    respond_to do |format|
      if @nisarga.update(nisarga_params)
        format.html { redirect_to @nisarga, notice: 'Nisarga was successfully updated.' }
        format.json { render :show, status: :ok, location: @nisarga }
      else
        format.html { render :edit }
        format.json { render json: @nisarga.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nisargas/1
  # DELETE /nisargas/1.json
  def destroy
    @nisarga.destroy
    respond_to do |format|
      format.html { redirect_to nisargas_url, notice: 'Nisarga was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nisarga
      @nisarga = Nisarga.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nisarga_params
      params.require(:nisarga).permit(:name)
    end
end

app/controllers/sharans_controller.rb
class SharansController < ApplicationController
  before_action :set_sharan, only: [:show, :edit, :update, :destroy]

  # GET /sharans
  # GET /sharans.json
  def index
    @sharans = Sharan.all
  end

  # GET /sharans/1
  # GET /sharans/1.json
  def show
  end

  # GET /sharans/new
  def new
    @sharan = Sharan.new
  end

  # GET /sharans/1/edit
  def edit
  end

  # POST /sharans
  # POST /sharans.json
  def create
    @sharan = Sharan.new(sharan_params)

    respond_to do |format|
      if @sharan.save
        format.html { redirect_to @sharan, notice: 'Sharan was successfully created.' }
        format.json { render :show, status: :created, location: @sharan }
      else
        format.html { render :new }
        format.json { render json: @sharan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sharans/1
  # PATCH/PUT /sharans/1.json
  def update
    respond_to do |format|
      if @sharan.update(sharan_params)
        format.html { redirect_to @sharan, notice: 'Sharan was successfully updated.' }
        format.json { render :show, status: :ok, location: @sharan }
      else
        format.html { render :edit }
        format.json { render json: @sharan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sharans/1
  # DELETE /sharans/1.json
  def destroy
    @sharan.destroy
    respond_to do |format|
      format.html { redirect_to sharans_url, notice: 'Sharan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sharan
      @sharan = Sharan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sharan_params
      params.require(:sharan).permit(:first, :last)
    end
end

app/controllers/vishnus_controller.rb
class VishnusController < ApplicationController
  before_action :set_vishnu, only: [:show, :edit, :update, :destroy]

  # GET /vishnus
  # GET /vishnus.json
  def index
    @vishnus = Vishnu.all
  end

  # GET /vishnus/1
  # GET /vishnus/1.json
  def show
  end

  # GET /vishnus/new
  def new
    @vishnu = Vishnu.new
  end

  # GET /vishnus/1/edit
  def edit
  end

  # POST /vishnus
  # POST /vishnus.json
  def create
    @vishnu = Vishnu.new(vishnu_params)

    respond_to do |format|
      if @vishnu.save
        format.html { redirect_to @vishnu, notice: 'Vishnu was successfully created.' }
        format.json { render :show, status: :created, location: @vishnu }
      else
        format.html { render :new }
        format.json { render json: @vishnu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vishnus/1
  # PATCH/PUT /vishnus/1.json
  def update
    respond_to do |format|
      if @vishnu.update(vishnu_params)
        format.html { redirect_to @vishnu, notice: 'Vishnu was successfully updated.' }
        format.json { render :show, status: :ok, location: @vishnu }
      else
        format.html { render :edit }
        format.json { render json: @vishnu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vishnus/1
  # DELETE /vishnus/1.json
  def destroy
    @vishnu.destroy
    respond_to do |format|
      format.html { redirect_to vishnus_url, notice: 'Vishnu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vishnu
      @vishnu = Vishnu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vishnu_params
      params.require(:vishnu).permit(:name, :designation, :company)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cheta_ns_helper.rb
module ChetaNsHelper
end

app/helpers/nisargas_helper.rb
module NisargasHelper
end

app/helpers/sharans_helper.rb
module SharansHelper
end

app/helpers/vishnus_helper.rb
module VishnusHelper
end

app/views/cheta_ns/_form.html.erb
<%= form_for(@chetan) do |f| %>
  <% if @chetan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chetan.errors.count, "error") %> prohibited this chetan from being saved:</h2>

      <ul>
      <% @chetan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :commit_id %><br>
    <%= f.number_field :commit_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cheta_ns/edit.html.erb
<h1>Editing Chetan</h1>

<%= render 'form' %>

<%= link_to 'Show', @chetan %> |
<%= link_to 'Back', chetans_path %>

app/views/cheta_ns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Chetans</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Commit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chetans.each do |chetan| %>
      <tr>
        <td><%= chetan.name %></td>
        <td><%= chetan.commit_id %></td>
        <td><%= link_to 'Show', chetan %></td>
        <td><%= link_to 'Edit', edit_chetan_path(chetan) %></td>
        <td><%= link_to 'Destroy', chetan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chetan', new_chetan_path %>

app/views/cheta_ns/new.html.erb
<h1>New Chetan</h1>

<%= render 'form' %>

<%= link_to 'Back', chetans_path %>

app/views/cheta_ns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @chetan.name %>
</p>

<p>
  <strong>Commit:</strong>
  <%= @chetan.commit_id %>
</p>

<%= link_to 'Edit', edit_chetan_path(@chetan) %> |
<%= link_to 'Back', chetans_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sandbox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/nisargas/_form.html.erb
<%= form_for(@nisarga) do |f| %>
  <% if @nisarga.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@nisarga.errors.count, "error") %> prohibited this nisarga from being saved:</h2>

      <ul>
      <% @nisarga.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nisargas/edit.html.erb
<h1>Editing Nisarga</h1>

<%= render 'form' %>

<%= link_to 'Show', @nisarga %> |
<%= link_to 'Back', nisargas_path %>

app/views/nisargas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Nisargas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nisargas.each do |nisarga| %>
      <tr>
        <td><%= nisarga.name %></td>
        <td><%= link_to 'Show', nisarga %></td>
        <td><%= link_to 'Edit', edit_nisarga_path(nisarga) %></td>
        <td><%= link_to 'Destroy', nisarga, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Nisarga', new_nisarga_path %>

app/views/nisargas/new.html.erb
<h1>New Nisarga</h1>

<%= render 'form' %>

<%= link_to 'Back', nisargas_path %>

app/views/nisargas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @nisarga.name %>
</p>

<%= link_to 'Edit', edit_nisarga_path(@nisarga) %> |
<%= link_to 'Back', nisargas_path %>

app/views/sharans/_form.html.erb
<%= form_for(@sharan) do |f| %>
  <% if @sharan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sharan.errors.count, "error") %> prohibited this sharan from being saved:</h2>

      <ul>
      <% @sharan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first %><br>
    <%= f.text_area :first %>
  </div>
  <div class="field">
    <%= f.label :last %><br>
    <%= f.text_area :last %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sharans/edit.html.erb
<h1>Editing Sharan</h1>

<%= render 'form' %>

<%= link_to 'Show', @sharan %> |
<%= link_to 'Back', sharans_path %>

app/views/sharans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sharans</h1>

<table>
  <thead>
    <tr>
      <th>First</th>
      <th>Last</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sharans.each do |sharan| %>
      <tr>
        <td><%= sharan.first %></td>
        <td><%= sharan.last %></td>
        <td><%= link_to 'Show', sharan %></td>
        <td><%= link_to 'Edit', edit_sharan_path(sharan) %></td>
        <td><%= link_to 'Destroy', sharan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sharan', new_sharan_path %>

app/views/sharans/new.html.erb
<h1>New Sharan</h1>

<%= render 'form' %>

<%= link_to 'Back', sharans_path %>

app/views/sharans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First:</strong>
  <%= @sharan.first %>
</p>

<p>
  <strong>Last:</strong>
  <%= @sharan.last %>
</p>

<%= link_to 'Edit', edit_sharan_path(@sharan) %> |
<%= link_to 'Back', sharans_path %>

app/views/vishnus/_form.html.erb
<%= form_for(@vishnu) do |f| %>
  <% if @vishnu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vishnu.errors.count, "error") %> prohibited this vishnu from being saved:</h2>

      <ul>
      <% @vishnu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :designation %><br>
    <%= f.text_field :designation %>
  </div>
  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vishnus/edit.html.erb
<h1>Editing Vishnu</h1>

<%= render 'form' %>

<%= link_to 'Show', @vishnu %> |
<%= link_to 'Back', vishnus_path %>

app/views/vishnus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Vishnus</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Designation</th>
      <th>Company</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vishnus.each do |vishnu| %>
      <tr>
        <td><%= vishnu.name %></td>
        <td><%= vishnu.designation %></td>
        <td><%= vishnu.company %></td>
        <td><%= link_to 'Show', vishnu %></td>
        <td><%= link_to 'Edit', edit_vishnu_path(vishnu) %></td>
        <td><%= link_to 'Destroy', vishnu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vishnu', new_vishnu_path %>

app/views/vishnus/new.html.erb
<h1>New Vishnu</h1>

<%= render 'form' %>

<%= link_to 'Back', vishnus_path %>

app/views/vishnus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vishnu.name %>
</p>

<p>
  <strong>Designation:</strong>
  <%= @vishnu.designation %>
</p>

<p>
  <strong>Company:</strong>
  <%= @vishnu.company %>
</p>

<%= link_to 'Edit', edit_vishnu_path(@vishnu) %> |
<%= link_to 'Back', vishnus_path %>